easy_admin:

  # =========================================
  # ============ Parametrage ================
  # =========================================

  # Liste des actions
  list:
    actions: ['edit', 'search', '-delete', 'show']
    title: 'CVB - %%entity_label%%'

  show:
    title: 'CVB - %%entity_label%% (#%%entity_id%%)'

  edit:
    title: 'CVB - %%entity_label%% (#%%entity_id%%)'

  # Format des dates
  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'

  # Titre haut de page
  site_name: 'CV Bien <span style="font-size: 70%;">Admin</span>'

  # Informations concernant l'utilisateur courant
  user:
    name_property_path: 'fullName'
    avatar_property_path: 'getProfilePicturePath'


  # =========================================
  # =============== Design ==================
  # =========================================
  design:
    brand_color: '#2331F0'
    assets:
      favicon: 'favicon.png'

    # Configuration du menu
    menu:
    - label: 'Users'
    - { entity: 'User', label: 'Accounts', icon: 'user'}

    - label: 'Referential'
    - { entity: 'Country', label: 'Countries', icon: 'globe' }
    - { entity: 'Diploma', label: 'Diplomas', icon: 'graduation-cap' }
    - { entity: 'JobType', label: 'Job type', icon: 'briefcase' }
    - { entity: 'Language', label: 'Language', icon: 'language' }
    - { entity: 'ProgLanguage', label: 'Programming Language', icon: 'code' }
    - { entity: 'Society', label: 'Society', icon: 'building' }

    - label: 'Mods'
    # Ajouter les entités concernant les modules


  # ==========================================
  # =============== Entites ==================
  # ==========================================
  entities:

    # --------------------- USERS ---------------------
    User:
      class: App\Entity\User
      disabled_actions: ['new']
      list:
        fields: ['spaceName', 'email', 'firstname', 'lastname', 'birthdate', 'isActive', 'isSearchable']
        sort: ['spaceName', 'ASC']
      edit:
        fields:
        - { type: 'tab', label: 'Account' }
        - 'email'
        - 'spaceName'
        - 'isActive'
        - 'isSearchable'
        - { type: 'tab', label: 'Personal' }
        - { type: 'group', columns: 6, label: 'Identity'}
        - 'firstname'
        - 'lastname'
        - { property: 'birthdate', type: 'birthday', label: 'Birthdate'}
        - { type: 'group', columns: 6, label: 'Job'}
        - 'status'
        - 'type'
        - { type: 'group', columns: 6, label: 'Address'}
        - { property: 'adress', type: 'text', label: 'Address'}
        - 'city'
        - 'cityCode'
        - 'country'
        - { type: 'group', columns: 6, label: 'Phone'}
        - 'phoneNumber'
        - 'proPhoneNumber'
      show:
        fields:
        - 'email'
        - 'spaceName'
        - 'isActive'
        - 'isSearchable'
        - 'firstname'
        - 'lastname'
        - 'birthdate'
        - 'status'
        - 'type'
        - { property: 'adress', type: 'text' }
        - 'city'
        - 'cityCode'
        - 'country'
        - 'phoneNumber'
        - 'proPhoneNumber'
        - 'userDiplomas'
        - 'links'
        - 'userProjects'
        - 'userLanguages'
        - 'userProgLanguages'
        - 'userSocieties'
        - 'date_creation_compte'
        - 'updatedAt'
        - 'date_derniere_connexion'

    UserDiploma:
      class: App\Entity\UserDiploma
      disabled_actions: ['new', 'edit', 'delete', 'search', 'list']
      list: ['id', 'user', 'diploma', 'dateOfGrant', 'mention']

    UserLink:
      class: App\Entity\Link
      disabled_actions: ['new', 'edit', 'delete', 'search', 'list']
      list: ['id', 'user', 'website', 'url', 'name', 'username']

    UserLanguage:
      class: App\Entity\UserLanguage
      disabled_actions: ['new', 'edit', 'delete', 'search', 'list']
      list: ['id', 'user', 'language', 'level']

    UserProgLanguage:
      class: App\Entity\UserProgLanguage
      disabled_actions: ['new', 'edit', 'delete', 'search', 'list']
      list: ['id', 'user', 'progLanguage', 'level']

    UserProject:
      class: App\Entity\UserProject
      disabled_actions: ['new', 'edit', 'delete', 'search', 'list']

    UserSociety:
      class: App\Entity\UserSociety
      disabled_actions: ['new', 'edit', 'delete', 'search', 'list']


    # --------------------- REFERENTIELS ---------------------
    # --- Parametrage JobType ---
    JobType:
      class: App\Entity\JobType
      list:
        fields: ['label']
        sort: ['label', 'ASC']
      form:
        fields:
        - 'label'
      show:
        fields:
        - 'id'
        - 'label'

    # --- Parametrage Diploma ---
    Diploma:
      class: App\Entity\Diploma
      list:
        fields: ['title', 'level', 'school',' country', 'isInternational']
        sort: ['title', 'ASC']
      form:
        fields:
        - 'title'
        - 'level'
        - 'school'
        - 'country'
        - 'isInternational'
      show:
        fields:
        - 'id'
        - 'title'
        - 'level'
        - 'isInternational'
        - 'school'
        - 'country'

    # --- Parametrage Pays ---
    Country:
      class: App\Entity\Country
      list:
        fields: ['name', 'users', 'id']
        sort: ['name', 'ASC']
      form:
        fields:
        - 'name'
      show:
        fields:
        - 'id'
        - 'name'

    # --- Parametrage Société ---
    Society:
      class: App\Entity\Society
      list:
        fields: ['name', 'adress', 'city', 'cityCode', 'country']
        sort: ['name', 'ASC']
      form:
        fields:
        - 'name'
        - 'adress'
        - 'city'
        - 'cityCode'
        - 'country'
      show:
        fields:
        - 'id'
        - 'name'
        - 'adress'
        - 'city'
        - 'cityCode'
        - 'country'

    # --- Parametrage Language ---
    Language:
      class: App\Entity\Language
      list:
        fields: ['name']
        sort: ['name', 'ASC']
      form:
        fields:
        - 'name'
      show:
        fields:
        - 'id'
        - 'name'

    # --- Parametrage ProgTechno ---
    ProgTechnology:
      class: App\Entity\ProgTechnology
      list:
        fields: ['label']
        sort: ['label', 'ASC']
      form:
        fields:
        - 'label'

    # --- Parametrage ProgLanguage ---
    ProgLanguage:
      class: App\Entity\ProgLanguage
      list:
        fields: ['name', 'type', 'parentProgLanguage', 'childProgLanguages']
        sort: ['name', 'ASC']
      form:
        fields:
        - 'name'
        - 'type'
        - 'parentProgLanguage'
        - 'childProgLanguages'
      show:
        fields:
        - 'id'
        - 'name'
        - 'type'
        - 'parentProgLanguage'
        - 'childProgLanguages'

    # --------------------- MODS ---------------------

