vich_uploader:
    db_driver: orm

    mappings:
        profilePictures:
            uri_prefix: /images/profilePictures
            upload_destination: '%kernel.project_dir%/public/images/profilePictures'
        bannerPictures:
            uri_prefix: /images/bannerPictures
            upload_destination: '%kernel.project_dir%/public/images/bannerPictures'
