version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=app_cvbien_dev
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=cvbienadmindevmdp
    ports:
    - "5432:5432"

volumes:
  db-data: {}