controllers:
  resource: ../../src/Controller/
  type: annotation
  prefix: /

controllers_back:
  resource: ../../src/Controller/Back
  type: annotation
  prefix: /back

controllers_front:
  resource: ../../src/Controller/Front
  type: annotation
  prefix: /dashboard